### ISSUE TITLE
Add URL to GitHub repo details

### ISSUE THREAD

**Issue by m-mohr** [stac-api-extensions/stac-api-extensions.github.io#2]
Would be nice to add URL https://stac-api-extensions.github.io to the GitHub repo details (under the repo description).

**Comment by philvarner** [comment]
There is one. Maybe I hadn't added the website url yet when you filed this. 

<img width="338" alt="image" src="https://user-images.githubusercontent.com/124996/218757135-9c03b5cc-a4d5-42a9-812c-f600a7866b81.png">
